### ISSUE TITLE
Update your code

### ISSUE THREAD

**Issue by Stepandanci** [Dimitrioglo/Test_Task_Ruby#1]
You wrote a good test task and you can update it.

0. Resolve discussions that I left in your previous commit. 
https://github.com/Dimitrioglo/Test_Task_Ruby/commit/9404e9c624d3a8b76e8fedac80bf17bb8f00a33d

1. Open a new Pull request for review.
We need to review your code and leave feedback.
You can clean the `master` branch in Github repository and    
open a new Pull request from branch `dev` to `master`.
It will make review your code much easier.

2. Read about Ruby style guide and update your code
https://github.com/rubocop-hq/ruby-style-guide
You also can install gem `rubocop` for faster updates.

3. No need to initiate `browser` 2 times.
In `main.rb` file create a new class (for example `Fibank`) and unite data aggregation logic.
Move from files `accounts.rb`, `transactions.rb` method for collect data   
`my_accounts`, `my_transactions` to `main.rb`

4. in `Accounts` and  `Transactions` class leave only methods for initializing objects and  
convert into hash

Example
```ruby
class Transactions
  attr_accessor :date, :description, :amount, :currency, :account_name

  def initialize(date, description, amount, currency, account_name)
    ...
    ...
  end

  def to_hash
    {
      date: @date,
      description: @description,
      ...
      ...
    }
  end
end
```

5. Accounts `balance` and transactions `amount` should be in float format `10.0`.

6. Your next step will be to write tests for your code.
You will test 2 parsing methods `parse_accounts` and `parse_transactions`
To make it easier for you to write tests, I recommend updating the structure of your code.

```ruby
class Fibank

  def execute
    connect
    fetch_accounts
    fetch_transactions
    print_data
  end

  def connect

  end

  def fetch_accounts
    # go to accounts HTML
    @accounts = parse_accounts(Nokogiri::HTML(browser.html))
  end

  def fetch_transactions
    @accounts.each do |account|
      # go to transactions HTML
      # add transactions to account
      parse_transactions(account, Nokogiri::HTML(browser.html))
    end
  end

  def parse_accounts(html)
    # add accounts here
  end

  def parse_transactions(account, html)
    # add transactions here
  end
end
```
Good luck.

**Comment by Stepandanci** [comment]
Updated test task with the more correct wording

[JRD Test task.pdf](https://github.com/Dimitrioglo/Test_Task_Ruby/files/3939097/JRD.Test.task.pdf)

**Comment by Stepandanci** [comment]
1) I recommend you to use Pry runtime developer console to handle your code.
Read about Pry here https://github.com/pry/pry

Run your code `ruby example.rb`  
use method binding.pry

```ruby
  def execute
    binding.pry # You stop at this line and can debug your code

    your code
  end
```
2) No need to take full HTML.
Use `Nokogiri::HTML.fragment` to extract page fragment with accounts data.

```ruby
accounts_html = Nokogiri::HTML.fragment(browser.div(class: "dashboard-main").html)
```

**Comment by Stepandanci** [comment]
Write tests for your code

Your last task to write tests.
1) Read about `Rspec`. It is a framework for test your code.

- https://rspec.info
- https://habr.com/ru/post/53264/
- https://relishapp.com/rspec/rspec-expectations/docs/built-in-matchers

2) Create Fibank_spec.rb file.
In `Fibank_spec.rb` file describe class `Fibank`.
Save 2 HTML files 'accounts.html' and 'transactions.html'.

3) Write specs for `parse_accounts` and `parse_transactions`.
Show parsing results.
Accounts and transactions count and a data example for 1 account and 1 transaction.

Code fragment example.
```ruby
html     = # File Read 'accounts.html' with Nokogiri HTML
accounts = Fibank.parse_accounts(html)

expect(accounts.count).to eq(2)

expect(accounts[0].to_hash).to eq(
  {
    ...
  }
)
```

Instruction how to save html file
1. press F12
2. find element
3. right click
4. copy outerHTML
5. save in `accounts.html`

![accounts_html](https://user-images.githubusercontent.com/29861352/66228848-2c820e00-e6e9-11e9-8cfe-2e637c4aae51.png)

**Comment by Stepandanci** [comment]
I recommend you to update your parsing methods.  
Take HTML fragment with Nokogiri and send it to the parsing method.

`html = Nokogiri::HTML.fragment(browser.div(class: "classname").html)`

Code example
```ruby
def parse_accounts(html)
  html.css('table#Example tr').each do |tr|
    name = tr.at_css('span.example-class').text
    ...

    @accounts << Account.new(name, ...)
  end
end
```

**Comment by Dimitrioglo** [comment]
@Stepandanci please check my new pull request.

**Comment by Stepandanci** [comment]
Read about Pry here https://github.com/pry/pry
Read about CSS selectors https://www.w3schools.com/cssref/css_selectors.asp

```ruby
def parse_accounts(html)
  html.css('table#dashboardAccounts tbody tr').each do |tr|
    # You should debug your code using Pry method
    binding.pry # just test nokogori objects using Css selectors
    name      = tr.css('p.name_exampleclass').text
    balance   = tr.css('div#balance_example_id').text

    @accounts << Account.new(...)
  end
```
